### ISSUE TITLE
Makefile and tox.ini run different suites through twisted trial

### ISSUE THREAD

**Issue by stefanor** [flexmock/flexmock#104]
Makefile tests trial against `tests/flexmock_pytest_test.py`:

https://github.com/flexmock/flexmock/blob/adc2419af992fe89aa21048aa8144f41baa16c99/Makefile#L47

tox tests trial against `tests/flexmock_test.py`:
https://github.com/flexmock/flexmock/blob/adc2419af992fe89aa21048aa8144f41baa16c99/tox.ini#L26

I'm assuming the Makefile should be changed to match (or deleted entirely).

**Comment by ollipa** [comment]
You are right! The file should be `flexmock_test.py` in the Makefile as well. I actually noticed this as well when I renamed the test files, so PR #102 fixes this issue.
