### ISSUE TITLE
Python3: problem in _verify_signature_match

### ISSUE THREAD

**Issue by obestwalter** [flexmock/flexmock#14]
This test case passes in 2.7.6 but reports a MethodSignatureError in 3.4.3:

file some_module:

```
class SomeClass:
    def __init__(self, a, b, c):
        pass
```

file test_fm_bug:

```
from flexmock import flexmock

from . import some_module


class SomeClass:
    def __init__(self, a, b, c):
        pass


def test_ok_mock():
    fm = flexmock(SomeClass)
    fm.should_receive('__init__').with_args(1, 2, 3)


def test_fm_bug():
    fm = flexmock(some_module)
    fm.should_receive('SomeClass').with_args(1, 2, 3)
```

error:

```
    def _verify_signature_match(self, *kargs, **kwargs):
    [...]
    if total_positional < minimum:
        raise MethodSignatureError(
            '%s requires at least %s arguments, expectation provided %s' %
>               (self.name, minimum, total_positional))
E           flexmock.MethodSignatureError: SomeClass requires at least 4 arguments, expectation provided 3
```

**Comment by obestwalter** [comment]
To clarify: 
- `test_ok_mock` is just for demonstration that it works if the class is in the same file. 
- `test_fm_bug` with the class used from imported module crashes

**Comment by bkabrda** [comment]
Thanks a lot for the report. As with the other bug, I'll try to address this when I get some time. Just to clarify, you are using flexmock version 0.10.1, is that correct?

**Comment by obestwalter** [comment]
> you are using flexmock version 0.10.1, is that correct?

Yes.

**Comment by bkabrda** [comment]
Fixed. Could you please verify that the fix works? I'll try to get to the other bug ASAP and then release a new version. Thanks!

**Comment by obestwalter** [comment]
installed from repo with `pip install https://github.com/bkabrda/flexmock/zipball/master` and prodcution test runs through as well now.
