### ISSUE TITLE
pycharm TestRunner and /junit xml support do not work correctly

### ISSUE THREAD

**Issue by frruit** [flexmock/flexmock#19]
Hi,
thanks for the cool mocking library.
My only problem is that the TestRunner output inside pycharm is invalid

![new bitmap image](https://cloud.githubusercontent.com/assets/10387712/23751670/a152e214-04d2-11e7-825f-84a6c66f5c7e.jpg)

I have seen that you add TestRunner support in the version 0.9.7 but with the Version 2016.2.3 it doesn't work. 

Any idea or workaround?

**Comment by frruit** [comment]
Hi, it's me again. Additional to the behavior in Pycharm i figured out that my junit xml has the same result. Tests where Flexmock identify an error like `foo() expected to be called exactly 1 times` are reported as passed. 

I use nose with python 3

**Comment by frruit** [comment]
okay, when i run my tests with the unittest runner, then everything is fine but not with the noserunner

**Comment by ollipa** [comment]
I'll close this since nose support will be removed in the upcoming release. Let us know if you have still issues using flexmock with Pycharm.
