### ISSUE TITLE
MockClass context __exit__ hides exceptions

### ISSUE THREAD

**Issue by lindycoder** [flexmock/flexmock#20]
Hi, i tried testing a method where my mock would be used as a context manager and the expected behavior is an exception raised inside the context.

What i found is that it doesn't because the __exit__ of the MockClass return "self" on exit, which seems to be hiding the exception.  I presume that python checks the result of the __exit__ and if something is returned it will assume that the __exit__ itself took care of the error?

Here's a sample:
```
from flexmock import flexmock


class EmptyExit(object):
    def __enter__(self, *args, **kwargs):
        pass

    def __exit__(self, *args, **kwargs):
        pass


class ReturningExit(object):
    def __enter__(self, *args, **kwargs):
        pass

    def __exit__(self, *args, **kwargs):
        return self


mock = flexmock()
returningexit = ReturningExit()
emptyexit = EmptyExit()


with mock:
    raise Exception("flexmock raised")

with returningexit:
    raise Exception("ReturningExit raised")

with emptyexit:
    raise Exception("EmptyExit raised")
```
running against python 2.7 and 3.5 makes the same error:
```
Traceback (most recent call last):
  File "....", line 32, in <module>
    raise Exception("EmptyExit raised")
Exception: EmptyExit raised
```

So should the __exit__ have only a "pass" in it maybe?

Right now the fact that __enter__ and __exit__ are declared in the mock makes it simple to use as a context, but it's impossible to do something such as `flexmock(obj).should_receive('__enter__').once()` to ensure the context is called.

What do you think?

**Comment by ollipa** [comment]
It seems that this was fixed in #25. Closing.
