### ISSUE TITLE
Adding Method to Class on Module level mock

### ISSUE THREAD

**Issue by Koschi13** [flexmock/flexmock#29]
Hi,

I'm currently trying to write a mock for a class on module level like this:
```
import Helper

mock = flexmock(Helper)
```
Helper is a class which is not implemented yet like this:
```
class Helper:
    pass
```
I'm trying to stub the method `help()` on this flexmock object like this:
```
mock.should_receive('help').and_return(True)
```
However this raises an exception:
```
flexmock.FlexmockError: <my_mock_module.Helper object at 0x7f8e77755860> does not have attribute help
```

How would I set an Method which does not exist with flexmock?

Tanks for the help :)

flexmock==0.10.4
python==3.7.3

**Comment by bkabrda** [comment]
Hmm, I've honestly never needed to do anything like this, so I'm a bit curious about the details of your usecase. Generally, there are two ways that flexmock works. Either you create a completely fake object, in which case you don't need to define the `Helper` class at all.

```
fake_helper = flexmock(help=lambda: True)
fake_helper.help()
```

Or you have the class defined, in which case I'm curious why you'd need to mock a method that doesn't actually exist on the class :)

**Comment by Koschi13** [comment]
@bkabrda let's say I have to work on `class Helper`, but I'm not able to implement it because it's a external class, all I know is how `Helper.help()` is working. 
So I would test my usage of this Method with a fake class, which should return True (for simplicity).

There are other Frameworks which can do this, but I just wanted to know if this is possible .
I'm currently writing my Thesis about Python test tools and this is one case of my comparison of the tools.

**Comment by bkabrda** [comment]
@Biskit1943 right, so here's what I'm asking: if the external class doesn't implement the `help` method, how do you know how that method is working? This is the point that confuses me. I don't see why you would mock a method that doesn't exist, since if it doesn't exist nobody can be using it, so what's the point in mocking it?

I'd be very interested to read your thesis when you finish that BTW, so please share it afterwards, if you can :)

**Comment by Koschi13** [comment]
@bkabrda sure you can read it, if you speek German ^^

The whole thing where I thought to use it, is when the specification states that there is a class `Helper` with that method `help()` whether or not it exists. My Method must use that method even if it does not exist yet. If I know what `help()` is doing it doesn't matter I if it is implemented or not.
I would need to mock the imported class `Helper` so that my module can be tested even if the method wasn't even instantiated.

Sure I could just write:
```
class Helper:
    def help():
        pass
```
but I was just curious if it might be possible, because I found other tools which can make this.

Anyway, if it is not working I'm fine with it. I just wanted to test some things :)

**Comment by bkabrda** [comment]
Hehe, I don't speak German, so no reading for me :)

I've been thinking about this situation and I think I might have a solution for you. Making sure that the mocked class actually has the mocked attribute/method is sort of a cornerstone of flexmock, so this is not likely to change. *But* I think you could actually mock the class's `__getattribute__` in this case to return a fake `help` function. Is that something that would work for your scenario?

**Comment by Koschi13** [comment]
How would you do that? I failed to get it working ^^

**Comment by bkabrda** [comment]
Something like:

```
import flexmock

class Helper(object):
    pass

def test_help():
    def fake_help():
        return "helping!"
    flexmock(Helper).should_receive("__getattribute__").with_args("help").and_return(fake_help)
    assert Helper().help() == "helping!"
```

It's true that it's a little bit clumsy, but I'm sure it could be improved further.

**Comment by Koschi13** [comment]
I'll include this in my Thesis and also mention your help :)
As far as the clumsiness concerns, I'm fine with it, as I have enough other things to do ^^

**Comment by Koschi13** [comment]
Well, I tested your solution a bit and I can't get it working. The Problem is the `__getattribute__` which expects two arguments but only one is provided:
```
flexmock.MethodSignatureError: __getattribute__ requires at least 2 arguments, expectation provided 1
```
With the following Code I get:
```
import flexmock

class Helper(object):
    pass

def test_help():
    helper = Helper()
    def fake_help():
        return "helping!"
    flexmock(helper).should_receive("__getattribute__").with_args("help").and_return(fake_help)
    assert helper.help() == "helping!"


if __name__ == '__main__':
    test_help()
```
>>>>
```
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    test_help()
  File "test.py", line 10, in test_help
    flexmock(helper).should_receive("__getattribute__").with_args("help").and_return(fake_help)
  File "/venv/lib/python3.7/site-packages/flexmock.py", line 740, in should_receive
    return self._create_expectation(obj, name)
  File "/venv/lib/python3.7/site-packages/flexmock.py", line 786, in _create_expectation
    self._update_method(expectation, name)
  File "/venv/lib/python3.7/site-packages/flexmock.py", line 854, in _update_method
    self._update_class_for_magic_builtins(obj, name)
  File "/venv/lib/python3.7/site-packages/flexmock.py", line 823, in _update_class_for_magic_builtins
    if _get_code(updated) != _get_code(original):
  File "/venv/lib/python3.7/site-packages/flexmock.py", line 1069, in _get_code
    return getattr(func, code)
AttributeError: 'wrapper_descriptor' object has no attribute '__code__'
```

So I don't think this will work :s

**Comment by bkabrda** [comment]
Yeah, this seems to be a problem with Python 3 implementation of the generic `object.__getattribute__` method which is actually a `wrapper_descriptor` and thus doesn't have a `__code__`, `func_code` or `im_func` attribute. I'll try to figure out a solution for this case.

**Comment by ollipa** [comment]
I'll close this for now, but if there is a convincing enough real-world use case for this feature, I would be happy to open this issue again.
