### ISSUE TITLE
Pytest test call duration is set to 0 when using flexmock

### ISSUE THREAD

**Issue by amaury-m-hw** [flexmock/flexmock#71]
Hello,

When importing flexmock in a pytest test suite, test call duration is systematically set to 0. test teardown and setup durations work fine.

# Steps to reproduce

python 3.6
pytest 6.2.4
flexmock 0.10.6

# Minimal repoducible example

```
import time
from flexmock import flexmock

def test_x():
    time.sleep(1)

```

And run `pytest --durations=0 -vv .`, which will output

```
================================================================================================ slowest durations ================================================================================================
0.00s teardown tests.py::test_x
0.00s setup    tests.py::test_x
0.00s call     tests::test_x

```
When removing `from flexmock import flexmock`, the command outputs

```
================================================================================================ slowest durations ================================================================================================
1.00s call     tests/test_task.py::test_x
0.00s teardown tests/test_task.py::test_x
0.00s setup    tests/test_task.py::test_x
```

Is there a way to fix it ? Thanks a lot for the help !

**Comment by ollipa** [comment]
Hello! This bug has already been fixed and it's waiting for a release. Once #70 is merged, we will make a new release.

**Comment by ollipa** [comment]
Fix released: https://pypi.org/project/flexmock/0.10.7/

**Comment by amaury-m-hw** [comment]
Awesome, thank you !
