### ISSUE TITLE
Modifier should_raise mentioned in documentation does not exist

### ISSUE THREAD

**Issue by vokracko** [flexmock/flexmock#85]
https://github.com/flexmock/flexmock/search?q=should_raise
https://github.com/flexmock/flexmock/blob/c7ab063102335a29af1bb9452c91b740eecfaa62/docs/user-guide.rst#L50

**Comment by ollipa** [comment]
Thanks for pointing out the mistake! It should say `and_raise` instead of `should_raise` there.
